name=L6474
version=1.0.0
author=MotorDriver, Matthew Miller
maintainer=Matthew Miller
sentence=Stepper motor driver library for Arduino Uno using X-NUCLEO-IHM01A1 shield.
paragraph=This L6474 library is compatible with the Arduino Uno R4 combined with one or several X-NUCLEO-IHM01A1 shields. It is designed for the Renesas architecture.
category=Device Control
url=https://github.com/mattykakes/L6474-stepper-motor-driver
architectures=renesas_uno